# Generated by Django 3.1 on 2020-10-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatename', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('supplername', models.DateTimeField(max_length=20)),
                ('queue_id', models.IntegerField(default=0)),
                ('queue_num', models.CharField(max_length=10)),
                ('showdisplay', models.IntegerField(default=0)),
                ('donotautomatic', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ворота',
                'verbose_name_plural': 'Ворота',
            },
        ),
    ]
