# Generated by Django 3.1 on 2020-11-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gates',
            name='supplername',
            field=models.CharField(max_length=80),
        ),
    ]
