# Generated by Django 3.1 on 2020-11-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_auto_20201123_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='gates',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
