# Generated by Django 3.1 on 2020-12-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0003_gates_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='gates',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
