# Generated by Django 3.1 on 2020-10-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queue_suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalcode', models.IntegerField()),
                ('objname', models.CharField(max_length=255)),
                ('ndow', models.IntegerField(default=0)),
                ('timeincome', models.DateTimeField(max_length=20)),
                ('created_date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('date_use_gate', models.DateField()),
                ('date_free_gate', models.DateField()),
                ('queue_num', models.CharField(max_length=10)),
                ('late', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очередь',
            },
        ),
    ]
