# Generated by Django 3.1 on 2020-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_suppliers',
            name='timeincome',
            field=models.TimeField(),
        ),
    ]
