# Generated by Django 3.1 on 2020-10-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_suppliers', '0002_auto_20201029_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_suppliers',
            name='date_free_gate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue_suppliers',
            name='date_use_gate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
