# Generated by Django 3.1 on 2020-12-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_suppliers', '0003_auto_20201029_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_suppliers',
            name='date_free_gate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue_suppliers',
            name='date_use_gate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
