# Generated by Django 3.1 on 2020-12-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_suppliers', '0004_auto_20201208_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_suppliers',
            name='export_1c',
            field=models.IntegerField(default=0),
        ),
    ]
