# Generated by Django 3.1 on 2020-10-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queue_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_kpp', models.IntegerField(verbose_name='Работа логики')),
                ('area_suppliers', models.IntegerField(verbose_name='Управлять через сканирование штрих кода')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
