# Generated by Django 3.1.3 on 2020-11-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_config', '0002_auto_20201117_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_config',
            name='area_suppliers',
            field=models.IntegerField(choices=[(0, 'Стандартный'), (1, 'Через сканирование')], default='0', verbose_name='Управлять через сканирование штрих кода'),
        ),
        migrations.AlterField(
            model_name='queue_config',
            name='not_kpp',
            field=models.IntegerField(choices=[(0, 'Автоматически'), (1, 'Вручную')], default='0', verbose_name='Работа логики'),
        ),
    ]
